/**
 * Intrihub Master Catalog Presets: Units, Colours, Dimensions, Finishes & Materials
 * Synchronized with Database & Multi-Category Storefront
 */

export interface CatalogColour {
  name: string;
  hexCode: string;
  textColor: "light" | "dark";
  categoryHint?: string;
}

export const CATALOG_COLOURS: CatalogColour[] = [
  { name: "White", hexCode: "#FFFFFF", textColor: "dark", categoryHint: "all" },
  { name: "Off White / Ivory", hexCode: "#FAF9F6", textColor: "dark", categoryHint: "paints" },
  { name: "Cream", hexCode: "#FFFDD0", textColor: "dark", categoryHint: "paints" },
  { name: "Beige", hexCode: "#F5F5DC", textColor: "dark", categoryHint: "tiles-stone" },
  { name: "Light Grey", hexCode: "#D3D3D3", textColor: "dark", categoryHint: "all" },
  { name: "Grey", hexCode: "#808080", textColor: "light", categoryHint: "all" },
  { name: "Dark Grey / Charcoal", hexCode: "#4A4A4A", textColor: "light", categoryHint: "all" },
  { name: "Black", hexCode: "#1A1A1A", textColor: "light", categoryHint: "all" },
  { name: "Silver / Chrome", hexCode: "#C0C0C0", textColor: "dark", categoryHint: "hardware" },
  { name: "Gold", hexCode: "#D4AF37", textColor: "dark", categoryHint: "hardware" },
  { name: "Rose Gold", hexCode: "#B76E79", textColor: "light", categoryHint: "hardware" },
  { name: "Antique Brass / Bronze", hexCode: "#CD7F32", textColor: "light", categoryHint: "hardware" },
  { name: "Brown", hexCode: "#8B4513", textColor: "light", categoryHint: "plywood-boards" },
  { name: "Dark Brown / Walnut", hexCode: "#4A2E18", textColor: "light", categoryHint: "plywood-boards" },
  { name: "Natural Wood / Teak", hexCode: "#C19A6B", textColor: "dark", categoryHint: "plywood-boards" },
  { name: "Light Blue", hexCode: "#ADD8E6", textColor: "dark", categoryHint: "paints" },
  { name: "Blue", hexCode: "#0055FF", textColor: "light", categoryHint: "all" },
  { name: "Navy Blue", hexCode: "#001F5B", textColor: "light", categoryHint: "all" },
  { name: "Green", hexCode: "#10B981", textColor: "light", categoryHint: "all" },
  { name: "Dark Green", hexCode: "#1E3F20", textColor: "light", categoryHint: "all" },
  { name: "Yellow", hexCode: "#FBBF24", textColor: "dark", categoryHint: "paints" },
  { name: "Orange", hexCode: "#F97316", textColor: "light", categoryHint: "all" },
  { name: "Red", hexCode: "#EF4444", textColor: "light", categoryHint: "all" },
  { name: "Maroon", hexCode: "#800000", textColor: "light", categoryHint: "paints" },
  { name: "Pink", hexCode: "#EC4899", textColor: "light", categoryHint: "paints" },
  { name: "Purple", hexCode: "#8B5CF6", textColor: "light", categoryHint: "paints" },
  { name: "Transparent / Clear", hexCode: "#E2E8F0", textColor: "dark", categoryHint: "chemicals" },
  { name: "Multicolour", hexCode: "#6366F1", textColor: "light", categoryHint: "all" },
];

export const CATALOG_UNITS = [
  "box",
  "sqft",
  "piece",
  "kg",
  "meter",
  "coil",
  "pack",
  "roll",
  "litre",
  "can",
  "sheet",
  "slab",
  "bucket",
  "drum",
  "bottle",
  "tube",
  "bag",
  "bundle",
  "set",
  "carton",
  "packet",
  "dozen",
  "ton",
];

export const CATALOG_DIMENSIONS = [
  // Tiles & Slabs
  "600x600 mm (2x2 ft)",
  "600x1200 mm (2x4 ft)",
  "800x1600 mm (2.6x5.2 ft)",
  "300x450 mm (1x1.5 ft)",
  "300x600 mm (1x2 ft)",
  "1200x1800 mm (4x6 ft)",
  "800x800 mm",
  "1200x2400 mm",
  "100x100 mm",
  "200x200 mm",
  "150x600 mm (Plank)",
  "150x900 mm (Wood Plank)",
  // Plywood & Sheet Boards
  "8x4 ft x 6mm",
  "8x4 ft x 9mm",
  "8x4 ft x 12mm",
  "8x4 ft x 16mm",
  "8x4 ft x 18mm",
  "8x4 ft x 19mm",
  "7x4 ft",
  "7x3 ft",
  // Electrical & Wires
  "90 m (Coil)",
  "180 m (Coil)",
  "1.0 sq mm",
  "1.5 sq mm",
  "2.5 sq mm",
  "4.0 sq mm",
  "6.0 sq mm",
  "10.0 sq mm",
  // Plumbing & Pipes
  "3 m (Pipe)",
  "6 m (Pipe)",
  "0.5 inch (15mm)",
  "0.75 inch (20mm)",
  "1.0 inch (25mm)",
  "1.25 inch (32mm)",
  "1.5 inch (40mm)",
  "2.0 inch (50mm)",
  "3.0 inch (75mm)",
  "4.0 inch (110mm)",
  // Volume & Packaging Weights
  "200 ml",
  "500 ml",
  "1 Litre",
  "4 Litre",
  "10 Litre",
  "20 Litre (Bucket)",
  "1 kg",
  "5 kg",
  "20 kg (Bag)",
  "50 kg (Bag)",
  "Custom Size",
];

export const CATALOG_FINISHES = [
  "Glossy",
  "Matt / Matte",
  "High Gloss",
  "Carving",
  "Satin",
  "Rustic",
  "Polished",
  "Wood Finish",
  "Marble Look",
  "Stone Texture",
  "Metallic",
  "Sugar Finish",
  "Lappato",
  "Full Body Vitrified",
  "Anti-Skid",
  "Smooth",
  "Semi-Gloss",
  "Eggshell",
];

export const CATALOG_MATERIALS = [
  "Glazed Vitrified (GVT)",
  "Polished Vitrified (PVT)",
  "Double Charge",
  "Ceramic",
  "Porcelain",
  "Natural Marble",
  "Granite",
  "Quartz",
  "Brass",
  "Stainless Steel (SS 304)",
  "CPVC / UPVC",
  "Copper",
  "Solid Wood",
  "Commercial Ply (MR)",
  "Waterproof Ply (BWP / BWR)",
  "MDF / HDF",
  "Acrylic",
  "Aluminum",
  "Standard Construction",
];
