import { prisma } from "../lib/prisma";

async function main() {
  console.log("Seeding / Ensuring test products with multi-variants...");

  // 1. Paint Product with 3 litre variants (1L, 4L, 10L)
  const paintSlug = "asian-paints-royale-luxury-emulsion-silky-sheen";
  await prisma.product.upsert({
    where: { slug: paintSlug },
    update: {
      name: "Asian Paints Royale Luxury Emulsion (Silky Sheen)",
      categorySlug: "paint-finishes",
      categoryName: "Paint & Finishes",
      material: "Water-based Emulsion",
      unitOfSale: "litre",
      description: "Asian Paints Royale Luxury Emulsion provides an exquisite, smooth, and ultra-durable finish with Teflon surface protection for luxury interior walls.",
      images: [
        "/placeholders/product.svg",
        "/placeholders/product.svg",
        "/placeholders/product.svg",
      ],
      pricePerSqft: 650,
      thickness: "Standard",
      usage: "Interior Living & Bedroom Walls",
      look: "Silky Sheen",
      inStock: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      status: "active",
      approvalStatus: "approved",
      variants: {
        deleteMany: {},
        create: [
          {
            size: "1L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "1 Litre",
            pricePerBox: 650,
            pricePerSqft: 650,
            sqftPerBox: 140, // 140 sqft coverage per 1L (2 coats)
            stockBoxes: 120,
            inStock: true,
          },
          {
            size: "4L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "4 Litre",
            pricePerBox: 2400,
            pricePerSqft: 600,
            sqftPerBox: 560,
            stockBoxes: 80,
            inStock: true,
          },
          {
            size: "10L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "10 Litre",
            pricePerBox: 5500,
            pricePerSqft: 550,
            sqftPerBox: 1400,
            stockBoxes: 45,
            inStock: true,
          },
          {
            size: "20L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "20 Litre",
            pricePerBox: 10200,
            pricePerSqft: 510,
            sqftPerBox: 2800,
            stockBoxes: 30,
            inStock: true,
          },
        ],
      },
    },
    create: {
      name: "Asian Paints Royale Luxury Emulsion (Silky Sheen)",
      slug: paintSlug,
      categorySlug: "paint-finishes",
      categoryName: "Paint & Finishes",
      material: "Water-based Emulsion",
      unitOfSale: "litre",
      description: "Asian Paints Royale Luxury Emulsion provides an exquisite, smooth, and ultra-durable finish with Teflon surface protection for luxury interior walls.",
      images: [
        "/placeholders/product.svg",
        "/placeholders/product.svg",
        "/placeholders/product.svg",
      ],
      pricePerSqft: 650,
      thickness: "Standard",
      usage: "Interior Living & Bedroom Walls",
      look: "Silky Sheen",
      inStock: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      status: "active",
      approvalStatus: "approved",
      variants: {
        create: [
          {
            size: "1L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "1 Litre",
            pricePerBox: 650,
            pricePerSqft: 650,
            sqftPerBox: 140,
            stockBoxes: 120,
            inStock: true,
          },
          {
            size: "4L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "4 Litre",
            pricePerBox: 2400,
            pricePerSqft: 600,
            sqftPerBox: 560,
            stockBoxes: 80,
            inStock: true,
          },
          {
            size: "10L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "10 Litre",
            pricePerBox: 5500,
            pricePerSqft: 550,
            sqftPerBox: 1400,
            stockBoxes: 45,
            inStock: true,
          },
          {
            size: "20L",
            finish: "Silky Sheen",
            color: "Ivory White",
            unit: "litre",
            attributeLabel: "Volume / Pack Size",
            attributeValue: "20 Litre",
            pricePerBox: 10200,
            pricePerSqft: 510,
            sqftPerBox: 2800,
            stockBoxes: 30,
            inStock: true,
          },
        ],
      },
    },
  });
  console.log("✓ Created/Updated Paint Product with 4 volume variants (1L, 4L, 10L, 20L)");

  // 2. Plywood Product with 3 dimension variants (6mm, 12mm, 19mm)
  const plySlug = "centuryply-club-prime-bwp-marine-plywood";
  await prisma.product.upsert({
    where: { slug: plySlug },
    update: {
      name: "CenturyPly Club Prime BWP Marine Plywood (IS 710)",
      categorySlug: "plywood-boards",
      categoryName: "Plywood & Boards",
      material: "Boiling Water Proof Hardwood",
      unitOfSale: "piece",
      description: "CenturyPly Club Prime is premium 100% boiling waterproof marine grade plywood with Glue Line Protection against borer and termites.",
      images: [
        "/placeholders/product.svg",
        "/placeholders/product.svg",
      ],
      pricePerSqft: 1650,
      thickness: "Multi-thickness",
      usage: "Kitchen Cabinets, Wardrobes & Wet Areas",
      look: "Smooth Hardwood Face",
      inStock: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      status: "active",
      approvalStatus: "approved",
      variants: {
        deleteMany: {},
        create: [
          {
            size: "6mm x 4x8ft",
            finish: "Standard",
            color: "Natural Wood",
            unit: "piece",
            attributeLabel: "Thickness & Sheet Size",
            attributeValue: "6mm (4x8 ft)",
            pricePerBox: 1650,
            pricePerSqft: 1650,
            sqftPerBox: 32, // 4ft x 8ft = 32 sqft sheet
            stockBoxes: 75,
            inStock: true,
          },
          {
            size: "12mm x 4x8ft",
            finish: "Standard",
            color: "Natural Wood",
            unit: "piece",
            attributeLabel: "Thickness & Sheet Size",
            attributeValue: "12mm (4x8 ft)",
            pricePerBox: 2800,
            pricePerSqft: 2800,
            sqftPerBox: 32,
            stockBoxes: 60,
            inStock: true,
          },
          {
            size: "19mm x 4x8ft",
            finish: "Standard",
            color: "Natural Wood",
            unit: "piece",
            attributeLabel: "Thickness & Sheet Size",
            attributeValue: "19mm (4x8 ft)",
            pricePerBox: 4200,
            pricePerSqft: 4200,
            sqftPerBox: 32,
            stockBoxes: 90,
            inStock: true,
          },
        ],
      },
    },
    create: {
      name: "CenturyPly Club Prime BWP Marine Plywood (IS 710)",
      slug: plySlug,
      categorySlug: "plywood-boards",
      categoryName: "Plywood & Boards",
      material: "Boiling Water Proof Hardwood",
      unitOfSale: "piece",
      description: "CenturyPly Club Prime is premium 100% boiling waterproof marine grade plywood with Glue Line Protection against borer and termites.",
      images: [
        "/placeholders/product.svg",
        "/placeholders/product.svg",
      ],
      pricePerSqft: 1650,
      thickness: "Multi-thickness",
      usage: "Kitchen Cabinets, Wardrobes & Wet Areas",
      look: "Smooth Hardwood Face",
      inStock: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      status: "active",
      approvalStatus: "approved",
      variants: {
        create: [
          {
            size: "6mm x 4x8ft",
            finish: "Standard",
            color: "Natural Wood",
            unit: "piece",
            attributeLabel: "Thickness & Sheet Size",
            attributeValue: "6mm (4x8 ft)",
            pricePerBox: 1650,
            pricePerSqft: 1650,
            sqftPerBox: 32,
            stockBoxes: 75,
            inStock: true,
          },
          {
            size: "12mm x 4x8ft",
            finish: "Standard",
            color: "Natural Wood",
            unit: "piece",
            attributeLabel: "Thickness & Sheet Size",
            attributeValue: "12mm (4x8 ft)",
            pricePerBox: 2800,
            pricePerSqft: 2800,
            sqftPerBox: 32,
            stockBoxes: 60,
            inStock: true,
          },
          {
            size: "19mm x 4x8ft",
            finish: "Standard",
            color: "Natural Wood",
            unit: "piece",
            attributeLabel: "Thickness & Sheet Size",
            attributeValue: "19mm (4x8 ft)",
            pricePerBox: 4200,
            pricePerSqft: 4200,
            sqftPerBox: 32,
            stockBoxes: 90,
            inStock: true,
          },
        ],
      },
    },
  });
  console.log("✓ Created/Updated Plywood Product with 3 dimension variants (6mm, 12mm, 19mm)");

  // 3. Tile Product with sqft/box
  const tileSlug = "kajaria-eternity-vitrified-royal-onyx-gold";
  await prisma.product.upsert({
    where: { slug: tileSlug },
    update: {
      name: "Kajaria Eternity Glazed Vitrified Tile (Royal Onyx Gold)",
      categorySlug: "floor-tiles",
      categoryName: "Floor Tiles",
      material: "Vitrified",
      unitOfSale: "box",
      description: "High-durability glazed vitrified tiles with mirror-polished nano gloss finish for residential living rooms, hallways, and commercial lobbies.",
      images: [
        "/placeholders/product.svg",
        "/placeholders/product.svg",
      ],
      pricePerSqft: 65,
      thickness: "9 mm",
      usage: "Floor / Living / Hall",
      look: "Onyx Marble",
      inStock: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      status: "active",
      approvalStatus: "approved",
      variants: {
        deleteMany: {},
        create: [
          {
            size: "600x600mm",
            finish: "Glossy",
            color: "Gold & White",
            unit: "box",
            attributeLabel: "Size",
            attributeValue: "600x600 mm",
            pricePerBox: 1040,
            pricePerSqft: 65,
            sqftPerBox: 16,
            stockBoxes: 150,
            inStock: true,
          },
          {
            size: "800x800mm",
            finish: "Glossy",
            color: "Gold & White",
            unit: "box",
            attributeLabel: "Size",
            attributeValue: "800x800 mm",
            pricePerBox: 1785,
            pricePerSqft: 85,
            sqftPerBox: 21,
            stockBoxes: 95,
            inStock: true,
          },
        ],
      },
    },
    create: {
      name: "Kajaria Eternity Glazed Vitrified Tile (Royal Onyx Gold)",
      slug: tileSlug,
      categorySlug: "floor-tiles",
      categoryName: "Floor Tiles",
      material: "Vitrified",
      unitOfSale: "box",
      description: "High-durability glazed vitrified tiles with mirror-polished nano gloss finish for residential living rooms, hallways, and commercial lobbies.",
      images: [
        "/placeholders/product.svg",
        "/placeholders/product.svg",
      ],
      pricePerSqft: 65,
      thickness: "9 mm",
      usage: "Floor / Living / Hall",
      look: "Onyx Marble",
      inStock: true,
      isBestseller: true,
      isNewArrival: true,
      isTrending: true,
      status: "active",
      approvalStatus: "approved",
      variants: {
        create: [
          {
            size: "600x600mm",
            finish: "Glossy",
            color: "Gold & White",
            unit: "box",
            attributeLabel: "Size",
            attributeValue: "600x600 mm",
            pricePerBox: 1040,
            pricePerSqft: 65,
            sqftPerBox: 16,
            stockBoxes: 150,
            inStock: true,
          },
          {
            size: "800x800mm",
            finish: "Glossy",
            color: "Gold & White",
            unit: "box",
            attributeLabel: "Size",
            attributeValue: "800x800 mm",
            pricePerBox: 1785,
            pricePerSqft: 85,
            sqftPerBox: 21,
            stockBoxes: 95,
            inStock: true,
          },
        ],
      },
    },
  });
  console.log("✓ Created/Updated Tile Product with 600x600 and 800x800 variants");

  console.log("\nAll test products successfully seeded!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
